"""Pydantic contracts for the LeetDecode API.

Three groups live here:

1. `SimplifiedProblem` / `SimplifiedExample` - the LLM output contract. This is
   the strict gate: every provider response must validate against it before it
   is cached or returned to anyone. A mismatch is an error, never a coercion.
2. `TranslateRequest` / `TranslateResponse` / `UsageResponse` / `ErrorResponse`
   - the HTTP contracts the Chrome extension talks to.
3. `gemini_json_schema()` / `groq_json_schema()` - provider-friendly renderings
   of the LLM contract, used to constrain generation. See `_base_schema()` for
   why they aren't just `SimplifiedProblem.model_json_schema()`.
"""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, StringConstraints

# A string that must carry actual content. Surrounding whitespace is trimmed
# first, so a value of "   " is rejected rather than silently stored as blank.
NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


# ---------------------------------------------------------------------------
# LLM output contract
# ---------------------------------------------------------------------------
# Both models set `extra="forbid"`, which rejects a response carrying keys we
# didn't ask for - the usual shape of a model that ignored the contract.
#
# Note on coercion: Pydantic v2 does not coerce across JSON types for `str`
# fields (an int input to a `str` field is an error, not a cast), so the SRS's
# "never silently coerce" requirement holds without strict mode. We avoid
# `strict=True` because it also disables `strip_whitespace`, which we want.


class SimplifiedExample(BaseModel):
    """One fully worked example for the simplified problem."""

    model_config = ConfigDict(extra="forbid")

    input: NonEmptyStr = Field(
        description="The example's input, written exactly as a caller would pass it.",
    )
    output: NonEmptyStr = Field(
        description="The value the solution returns for that input.",
    )
    explanation: NonEmptyStr = Field(
        description="Plain-English walkthrough of why that input produces that output.",
    )


class SimplifiedProblem(BaseModel):
    """The structured plain-English restatement of a LeetCode problem.

    This is exactly the JSON contract in the SRS. It is what gets stored in
    `problems_cache.simplified_json` and what the popup renders.
    """

    model_config = ConfigDict(extra="forbid")

    what_you_need_to_do: NonEmptyStr = Field(
        description=(
            "The task restated in plain English, no jargon, as if explaining to "
            "someone who has never seen a coding problem before."
        ),
    )
    input: NonEmptyStr = Field(
        description="What the function receives, in plain English.",
    )
    output: NonEmptyStr = Field(
        description="What the function must return, in plain English.",
    )
    important_notes: list[NonEmptyStr] = Field(
        min_length=1,
        description=(
            "Constraints, edge cases and gotchas a beginner would miss. "
            "At least one; two to four is typical."
        ),
    )
    example: SimplifiedExample = Field(
        description="A single worked example demonstrating the task.",
    )


# ---------------------------------------------------------------------------
# HTTP contracts
# ---------------------------------------------------------------------------


class TranslateRequest(BaseModel):
    """Body of POST /translate."""

    model_config = ConfigDict(extra="forbid")

    install_id: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=8, max_length=128)
    ] = Field(
        description="Anonymous per-install identifier generated by the extension.",
    )
    raw_text: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=20, max_length=20_000)
    ] = Field(
        description=(
            "The full pasted problem text: title, description, examples, constraints."
        ),
    )


class TranslateResponse(BaseModel):
    """Successful response from POST /translate."""

    model_config = ConfigDict(extra="forbid")

    source: Literal["cache", "llm"] = Field(
        description="'cache' if served from problems_cache, 'llm' if freshly generated.",
    )
    data: SimplifiedProblem


class UsageResponse(BaseModel):
    """Response from GET /usage/{install_id}."""

    model_config = ConfigDict(extra="forbid")

    free_calls_used: int = Field(ge=0)
    free_calls_remaining: int = Field(ge=0)


class ErrorResponse(BaseModel):
    """Error envelope, e.g. the 403 QUOTA_EXCEEDED body."""

    model_config = ConfigDict(extra="forbid")

    error: str = Field(description="Stable machine-readable code, e.g. QUOTA_EXCEEDED.")
    message: str = Field(description="Human-readable text the popup can display.")


# ---------------------------------------------------------------------------
# Provider-facing schema
# ---------------------------------------------------------------------------

# Validation-only keywords Pydantic emits that provider schema parsers reject or
# ignore. Validation is our job, not the provider's, so they are stripped before
# the schema is sent upstream.
_CONSTRAINT_KEYWORDS = frozenset(
    {
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "pattern",
        "format",
        "default",
        "examples",
        "title",
    }
)

# Gemini's parser additionally rejects `additionalProperties`. Groq's strict mode
# *requires* it, so the two providers get different renderings of one contract.
_GEMINI_DROP = _CONSTRAINT_KEYWORDS | {"additionalProperties"}


def _inline_refs(node: Any, defs: dict[str, Any]) -> Any:
    """Recursively replace `$ref` pointers with the definition they point at.

    Pydantic hoists nested models (here, `SimplifiedExample`) into `$defs` and
    references them. Provider schema parsers vary in their `$ref` support, so
    we inline everything and hand over a self-contained tree.
    """
    if isinstance(node, list):
        return [_inline_refs(item, defs) for item in node]
    if not isinstance(node, dict):
        return node

    if "$ref" in node:
        ref_name = node["$ref"].rsplit("/", 1)[-1]
        resolved = _inline_refs(defs[ref_name], defs)
        # Sibling keys (e.g. a field-level "description") win over the target's.
        siblings = {k: v for k, v in node.items() if k != "$ref"}
        return {**resolved, **siblings}

    return {k: _inline_refs(v, defs) for k, v in node.items()}


def _strip(node: Any, drop: frozenset[str]) -> Any:
    """Recursively remove the given keywords."""
    if isinstance(node, list):
        return [_strip(item, drop) for item in node]
    if not isinstance(node, dict):
        return node
    return {k: _strip(v, drop) for k, v in node.items() if k not in drop}


def _base_schema(drop: frozenset[str]) -> dict[str, Any]:
    """`SimplifiedProblem` as a self-contained schema, minus `drop`.

    Deliberately not `SimplifiedProblem.model_json_schema()` verbatim: that
    carries `$defs`/`$ref` indirection and constraint keywords whose support
    differs between providers, and an unsupported keyword can fail the request
    outright.

    What goes upstream is a generation *hint* describing shape - object
    structure, property names, types and descriptions. The authoritative check
    stays local, in `SimplifiedProblem`, which every response must pass. One
    source of truth, rendered per provider.
    """
    raw = SimplifiedProblem.model_json_schema()
    defs = raw.pop("$defs", {})
    schema = _strip(_inline_refs(raw, defs), drop)
    # The root description is just this class's docstring, which talks about
    # internals ("problems_cache", "the SRS"). Per-property descriptions are
    # useful to the model; that one is noise. The system prompt does the framing.
    schema.pop("description", None)
    return schema


def gemini_json_schema() -> dict[str, Any]:
    """Schema for Gemini's `response_format`, without `additionalProperties`."""
    return _base_schema(_GEMINI_DROP)


def groq_json_schema() -> dict[str, Any]:
    """Schema for Groq's `json_schema` response format.

    Keeps `additionalProperties: false` (emitted by `extra="forbid"`), which
    Groq's `strict: true` mode requires and Gemini rejects.
    """
    return _base_schema(_CONSTRAINT_KEYWORDS)
