"""Pydantic contracts for the LeetDecode API.

Three groups live here:

1. `SimplifiedProblem` / `SimplifiedExample` - the LLM output contract. This is
   the strict gate: every provider response must validate against it before it
   is cached or returned to anyone. A mismatch is an error, never a coercion.
2. `TranslateRequest` / `TranslateResponse` / `UsageResponse` / `ErrorResponse`
   - the HTTP contracts the Chrome extension talks to.
3. `gemini_json_schema()` - a provider-friendly rendering of the LLM contract,
   used to constrain Gemini's generation. See its docstring for why it isn't
   just `SimplifiedProblem.model_json_schema()`.
"""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, StringConstraints

# A string that must carry actual content. Surrounding whitespace is trimmed
# first, so a value of "   " is rejected rather than silently stored as blank.
NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


# ---------------------------------------------------------------------------
# LLM output contract
# ---------------------------------------------------------------------------
# Both models set `extra="forbid"`, which rejects a response carrying keys we
# didn't ask for - the usual shape of a model that ignored the contract.
#
# Note on coercion: Pydantic v2 does not coerce across JSON types for `str`
# fields (an int input to a `str` field is an error, not a cast), so the SRS's
# "never silently coerce" requirement holds without strict mode. We avoid
# `strict=True` because it also disables `strip_whitespace`, which we want.


class SimplifiedExample(BaseModel):
    """One fully worked example for the simplified problem."""

    model_config = ConfigDict(extra="forbid")

    input: NonEmptyStr = Field(
        description="The example's input, written exactly as a caller would pass it.",
    )
    output: NonEmptyStr = Field(
        description="The value the solution returns for that input.",
    )
    explanation: NonEmptyStr = Field(
        description="Plain-English walkthrough of why that input produces that output.",
    )


class SimplifiedProblem(BaseModel):
    """The structured plain-English restatement of a LeetCode problem.

    This is exactly the JSON contract in the SRS. It is what gets stored in
    `problems_cache.simplified_json` and what the popup renders.
    """

    model_config = ConfigDict(extra="forbid")

    what_you_need_to_do: NonEmptyStr = Field(
        description=(
            "The task restated in plain English, no jargon, as if explaining to "
            "someone who has never seen a coding problem before."
        ),
    )
    input: NonEmptyStr = Field(
        description="What the function receives, in plain English.",
    )
    output: NonEmptyStr = Field(
        description="What the function must return, in plain English.",
    )
    important_notes: list[NonEmptyStr] = Field(
        min_length=1,
        description=(
            "Constraints, edge cases and gotchas a beginner would miss. "
            "At least one; two to four is typical."
        ),
    )
    example: SimplifiedExample = Field(
        description="A single worked example demonstrating the task.",
    )


# ---------------------------------------------------------------------------
# HTTP contracts
# ---------------------------------------------------------------------------


class TranslateRequest(BaseModel):
    """Body of POST /translate."""

    model_config = ConfigDict(extra="forbid")

    install_id: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=8, max_length=128)
    ] = Field(
        description="Anonymous per-install identifier generated by the extension.",
    )
    raw_text: Annotated[
        str, StringConstraints(strip_whitespace=True, min_length=20, max_length=20_000)
    ] = Field(
        description=(
            "The full pasted problem text: title, description, examples, constraints."
        ),
    )


class TranslateResponse(BaseModel):
    """Successful response from POST /translate."""

    model_config = ConfigDict(extra="forbid")

    source: Literal["cache", "llm"] = Field(
        description="'cache' if served from problems_cache, 'llm' if freshly generated.",
    )
    data: SimplifiedProblem


class UsageResponse(BaseModel):
    """Response from GET /usage/{install_id}."""

    model_config = ConfigDict(extra="forbid")

    free_calls_used: int = Field(ge=0)
    free_calls_remaining: int = Field(ge=0)


class ErrorResponse(BaseModel):
    """Error envelope, e.g. the 403 QUOTA_EXCEEDED body."""

    model_config = ConfigDict(extra="forbid")

    error: str = Field(description="Stable machine-readable code, e.g. QUOTA_EXCEEDED.")
    message: str = Field(description="Human-readable text the popup can display.")


# ---------------------------------------------------------------------------
# Provider-facing schema
# ---------------------------------------------------------------------------

# JSON Schema keywords Pydantic emits that Gemini's structured-output schema
# parser does not accept. They are validation concerns, and validation is our
# job, not the provider's - so they are stripped before the schema is sent.
_UNSUPPORTED_KEYWORDS = frozenset(
    {
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "pattern",
        "format",
        "default",
        "examples",
        "additionalProperties",
        "title",
    }
)


def _inline_refs(node: Any, defs: dict[str, Any]) -> Any:
    """Recursively replace `$ref` pointers with the definition they point at.

    Pydantic hoists nested models (here, `SimplifiedExample`) into `$defs` and
    references them. Provider schema parsers vary in their `$ref` support, so
    we inline everything and hand over a self-contained tree.
    """
    if isinstance(node, list):
        return [_inline_refs(item, defs) for item in node]
    if not isinstance(node, dict):
        return node

    if "$ref" in node:
        ref_name = node["$ref"].rsplit("/", 1)[-1]
        resolved = _inline_refs(defs[ref_name], defs)
        # Sibling keys (e.g. a field-level "description") win over the target's.
        siblings = {k: v for k, v in node.items() if k != "$ref"}
        return {**resolved, **siblings}

    return {k: _inline_refs(v, defs) for k, v in node.items()}


def _strip_unsupported(node: Any) -> Any:
    """Drop validation-only keywords, recursively."""
    if isinstance(node, list):
        return [_strip_unsupported(item) for item in node]
    if not isinstance(node, dict):
        return node
    return {
        k: _strip_unsupported(v)
        for k, v in node.items()
        if k not in _UNSUPPORTED_KEYWORDS
    }


def gemini_json_schema() -> dict[str, Any]:
    """The `SimplifiedProblem` contract as a self-contained, portable JSON Schema.

    Deliberately not `SimplifiedProblem.model_json_schema()` verbatim. That
    output carries `$defs`/`$ref` indirection and constraint keywords
    (`minLength`, `minItems`, ...) that Gemini's schema parser rejects or
    ignores - and an unsupported keyword can fail the request outright.

    So the schema we send upstream is a generation *hint* describing shape:
    object structure, property names, types and descriptions. The authoritative
    check stays local, in `SimplifiedProblem`, which every response must pass.
    One source of truth, rendered two ways.

    The Grok adapter does not use this: `xai-sdk` accepts the Pydantic model
    class directly and builds its own schema.
    """
    raw = SimplifiedProblem.model_json_schema()
    defs = raw.pop("$defs", {})
    schema = _strip_unsupported(_inline_refs(raw, defs))
    # The root description is just this class's docstring, which talks about
    # internals ("problems_cache", "the SRS"). Per-property descriptions are
    # useful to the model; that one is noise. The system prompt does the framing.
    schema.pop("description", None)
    return schema
